---
dependencies:

galaxy_info:
  author: opstree
  description: Mybb Setup
  company: "OpsTree"
  min_ansible_version: 1.9
  platforms:
  - name: EL
    versions:
    - 6
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  categories:
    - development
    - packaging

