---
# tasks file for puppet.sync

- name: Configure hostname ....
  command: hostname {{ hostname }}

<<<<<<< HEAD
- name:  hostname configured....
  command: /etc/init.d/network restart

- lineinfile: dest=/etc/hosts line={{ Add_line }}
=======
- lineinfile: dest=/etc/hosts line="52.24.81.83 foreman.bigparser.com" 
>>>>>>> 0884ad38209515ec7764c4f3dc05145856971081

- name: Install Puppet repo ....
  get_url: url=https://yum.puppetlabs.com/puppetlabs-release-el-7.noarch.rpm dest=/tmp

- name: Extracting puppet ....
  command: rpm -i /tmp/puppetlabs-release-el-7.noarch.rpm

- name: Install Puppet agent ...
  yum: "name=puppet state=installed"

- name: Copy auth.conf....
  template: src=auth.conf dest=/etc/puppet/auth.conf

- name: Copy puppet.conf ....
  template: src=puppet.conf dest=/etc/puppet/puppet.conf

- name: Enable puppet ....
  command: puppet agent --enable 

- name: Sync puppet ....
  command: puppet agent -t --debug
